version: '2.4'
services:
  zte_connector:
    network_mode: bridge
    image: 'sstarzh/zte-connector:alpine.latest'
    ports:
      - "51820:51820/udp"
      - "51821:51821"
    tty: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    command: tenant_name connector_name auth_key api_key tenantID
    user: root
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:51821/health || exit 1
      interval: 30s
      retries: 1
      start_period: 20s
      timeout: 10s