version: '2.4'
services:
  zte_connector:
    image: 'sstarzh/zte-connector:ubuntu.latest'
    tty: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    command: tenant_name connector_name auth_key api_key tenantID
    user: root
    restart: on-failure
    ports:
      - '51820:51820/udp'
    networks:
      lannet:
        ipv4_address: <ip address in LAN>
    devices:
      - '/dev/net/tun:/dev/net/tun'